/*

Description: Store the constant data which we can re-use on any class. JIRA : POC-2354
Created Date: 23/10/2022
Created By:   Anil Gumma

*/
public class Constants {

    public static final Decimal TEN_THOUSAND      = 10000;
    public static final Decimal FIFTY_THOUSAND    = 50000;
    public static final Decimal TEN_FIVE_THOUSAND = 25000;
    public static final String GOLD              = 'GOLD';
    public static final String SILVER            = 'SILVER';
    public static final String BRONZE            = 'BRONZE';

}